config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
   get 'comentarios/new.:id' => 'get#new'

  resources :articulos

end

app/models/articulo.rb
class Articulo < ActiveRecord::Base
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  before_action :set_articulo, only: [:show, :edit, :update, :destroy]

  # GET /articulos
  # GET /articulos.json
  def index
    @articulos = Articulo.all
  end

  # GET /articulos/1
  # GET /articulos/1.json
  def show
       @comentarios = Comentario.select("articulo_id, cuerpo").where(:articulo_id => params[:id]);
  end

  # GET /articulos/new
  def new
    @articulo = Articulo.new
  end

  # GET /articulos/1/edit
  def edit
  end

  # POST /articulos
  # POST /articulos.json
  def create
    @articulo = Articulo.new(articulo_params)

    respond_to do |format|
      if @articulo.save
        format.html { redirect_to @articulo, notice: 'Articulo was successfully created.' }
        format.json { render :show, status: :created, location: @articulo }
      else
        format.html { render :new }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articulos/1
  # PATCH/PUT /articulos/1.json
  def update
    respond_to do |format|
      if @articulo.update(articulo_params)
        format.html { redirect_to @articulo, notice: 'Articulo was successfully updated.' }
        format.json { render :show, status: :ok, location: @articulo }
      else
        format.html { render :edit }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articulos/1
  # DELETE /articulos/1.json
  def destroy
    @articulo.destroy
    respond_to do |format|
      format.html { redirect_to articulos_url, notice: 'Articulo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articulo
      @articulo = Articulo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def articulo_params
      params.require(:articulo).permit(:titulo, :cuerpo)
    end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
    @comentario.articulo_id=params[:format]
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:articulo_id, :cuerpo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/articulos/_form.html.erb
<%= form_for(@articulo) do |f| %>
  <% if @articulo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@articulo.errors.count, "error") %> prohibited this articulo from being saved:</h2>

      <ul>
      <% @articulo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :cuerpo %><br>
    <%= f.text_area :cuerpo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articulos/edit.html.erb
<h1>Editing articulo</h1>

<%= render 'form' %>

<%= link_to 'Show', @articulo %> |
<%= link_to 'Back', articulos_path %>

app/views/articulos/index.html.erb
<h1>Listing articulos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Cuerpo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articulos.each do |articulo| %>
      <tr>
        <td><%= articulo.titulo %></td>
        <td><%= articulo.cuerpo %></td>
        <td><%= link_to 'Show', articulo %></td>
        <td><%= link_to 'Edit', edit_articulo_path(articulo) %></td>
        <td><%= link_to 'Destroy', articulo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Articulo', new_articulo_path %>

app/views/articulos/new.html.erb
<h1>New articulo</h1>

<%= render 'form' %>

<%= link_to 'Back', articulos_path %>

app/views/articulos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @articulo.titulo %>
</p>

<p>
  <strong>Cuerpo:</strong>
  <%= @articulo.cuerpo %>
</p>

<%= link_to 'Edit', edit_articulo_path(@articulo) %> |
<%= link_to 'Back', articulos_path %>

<h1>Listing comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Articulo</th>
      <th>Cuerpo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.articulo_id %></td>
        <td><%= comentario.cuerpo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :articulo_id %><br>
    <%= f.number_field :articulo_id %>
  </div>
  <div class="field">
    <%= f.label :cuerpo %><br>
    <%= f.text_area :cuerpo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<h1>Listing comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Articulo</th>
      <th>Cuerpo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.articulo_id %></td>
        <td><%= comentario.cuerpo %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Articulo:</strong>
  <%= @comentario.articulo_id %>
</p>

<p>
  <strong>Cuerpo:</strong>
  <%= @comentario.cuerpo %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>
<%= link_to 'Nuevo Comentario', new_comentario_path(@articulo) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>